---
title: "Plotly and flexdashboard"
output: html_document
date: "2025-10-21"
theme: journal
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Let's load the AirBnB dataset.
```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb |>
  mutate(
    rating=review_scores_location / 2
  ) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long
  ) |>
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt", 
    price<=500,
    price>=100
  )
```


Let's make a scatterplot!!!! But interactive this time.
```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "blue")
```


## ggplotly
Can be a handy way to make a plot quickly. Just for you.
Don't use this often.
```{r}
ggp_scatterplot = 
nyc_airbnb |>
  ggplot(aes(x=lat, y=long, color=price)) +
  geom_point()

ggplotly(ggp_scatterplot)
```


## Create a dashboard
```{r}

```

